apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: openai
spec:
  type: conversation.openai
  version: v1
  metadata:
    - name: key
      secretKeyRef:
        name: openai-api-key
        key: openai-api-key
    - name: model
      value: "gpt-4o-mini"
auth:
  secretStore: localsecretstore
